### ISSUE TITLE
Need help, examples for RPi not working at all!

### ISSUE THREAD

**Issue by anglerfish27** [cdjq/DFRobot_C4001#3]
Hello I have the C4001 human presence sensor and I am trying to use it on a Raspberry PI. So far the code from github is not working (the examples).

 

First Question:

The two dip switches on the device, how should they positioned? If I wanted to use I2C how should they be set, if I wanted to use UART how should they be set?

 

The python code when imported into Thonny throws a bunch of errors, many were due to incompatible line spacing I had to manually fix them.

 

IF using I2C which GPIO pins should I use on the Raspberry Pi? 

IF using UART which GPIO pins should I use?

 

I noticed in the code when it appears to use I2C it doesn't ask for any GPIO PIN numbers (SDA, CLK) so I'm confused how this is supposed to work. I used CuteCom to connect and I saw some data coming through via serial, it was mostly just:

$DFHPD,0, , , *␍␊

$DFHPD,1, , , *␍␊

 

Please help and fix the code, I cannot use the product!!

 

Right now I have the dip switches set to I2C and 0x2B (both switches in the down position). I try and run the motion_dectection.py example provided and I get the follow warnings (no errors technically):

motion_detection.py
Line 14 : Unused import os
It looks like the imported module or variable is not used.
Line 17 : Unused RPi.GPIO imported as GPIO

 

However in the REPL I get many errors and even more errors listed on “assistant” pane of Thonny for the main DFRobot .py file.

 

REPL SHELL:

```
Traceback (most recent call last):
 File "/home/fed/Desktop/Motion_Detect/DFRobot_C4001-main/python/raspberrypi/examples/motion_detection.py", line 73, in <module>
   loop()
 File "/home/fed/Desktop/Motion_Detect/DFRobot_C4001-main/python/raspberrypi/examples/motion_detection.py", line 66, in loop
   if 1 == radar.motion_detection():
 File "/home/fed/Desktop/Motion_Detect/DFRobot_C4001-main/python/raspberrypi/examples/DFRobot_C4001.py", line 176, in motion_detection
   return rslt[0]&0x01
TypeError: 'int' object is not subscriptable
```

 

And a ton of issues in the assistant pane:

 

```
DFRobot_C4001.py
Line 138 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 146 : Either all return statements in a function should return an expression, or none of them should.
According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)
Line 152 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 155 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 158 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 161 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 164 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 167 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 175 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 178 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 182 : Either all return statements in a function should return an expression, or none of them should.
According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)
Line 191 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 194 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 197 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 199 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 201 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 211 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 222 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 229 : Either all return statements in a function should return an expression, or none of them should.
According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)
Line 235 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 246 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 254 : Either all return statements in a function should return an expression, or none of them should.
According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)
Line 264 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 276 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 285 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 305 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 320 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 330 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 339 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 348 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 373 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 386 : Either all return statements in a function should return an expression, or none of them should.
According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)
Line 399 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 411 : Either all return statements in a function should return an expression, or none of them should.
According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)
Line 449 : Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
Line 450 : Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
Line 451 : Incompatible types in assignment (expression has type "float", variable has type "int")  [assignment]
Line 470 : Either all return statements in a function should return an expression, or none of them should.
According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)
Line 472 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 478 : Redefining name 'status' from outer scope (line 66)
It looks like the local variable is hiding a global variable with the same name.
Most likely there is nothing wrong with this. I just wanted to remind you that you can't access the global variable like this. If you knew it then please ignore the warning.
If you don't want to see this reminder in the future, then add "redefined-outer-name" (without quotes) into "Tools → Options → Assistant → Disabled checks".
Line 482 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 492 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 499 : Either all return statements in a function should return an expression, or none of them should.
According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)
Line 580 : Unused argument 'count'
If you want to keep the argument and silence this warning, then add comment "#pylint: disable=unused-argument" as first line in your function body.
Line 582 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 584 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 585 : "DFRobot_C4001" has no attribute "read_reg"  [attr-defined]
Line 586 : Unused variable 'len'
Looks like the variable is defined (or imported) but not used.
Line 589 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 594 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 596 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 599 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 601 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 603 : "DFRobot_C4001" has no attribute "write_reg"  [attr-defined]
Line 620 : Either all return statements in a function should return an expression, or none of them should.
According to PEP8, if any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None, and an explicit return statement should be present at the end of the function (if reachable)
Line 629 : Unused private member `DFRobot_C4001_UART.__uart_i2c`
It looks like the private member of a class is defined but not used.
Line 630 : Unused private member `DFRobot_C4001_UART.__Baud`
It looks like the private member of a class is defined but not used.
Line 633 : Unused argument 'reg'
If you want to keep the argument and silence this warning, then add comment "#pylint: disable=unused-argument" as first line in your function body.
Line 643 : Unused argument 'reg'
If you want to keep the argument and silence this warning, then add comment "#pylint: disable=unused-argument" as first line in your function body.

motion_detection.py
Line 14 : Unused import os
It looks like the imported module or variable is not used.
Line 17 : Unused RPi.GPIO imported as GPIO
```

**Comment by olavt** [comment]
"The two dip switches on the device, how should they positioned? If I wanted to use I2C how should they be set, if I wanted to use UART how should they be set?"

The top switch:
Left: UART
Right: I2C

The bottom switch:
Left: Use I2C address 0x2A
Right: Use I2C address 0x2B
